packages:
  - 'packages/*'
  - 'sites/*'

catalog:
  svelte: ^5.39.5
  typescript: ^5.9.2
  vite: ^7.1.7
  '@sveltejs/kit': ^2.43.1
  '@sveltejs/adapter-auto': ^6.1.0
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@types/node': ^24.10.0
  svelte-check: ^4.3.3

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
